id: I1EDE4407
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:57:33.328167
last_modified: 2023-02-08 14:57:33.328293
source_metadata:
  title: 'RK: Bodhisatvapiṭaka'
  language: bo
bases:
  A26F:
    base_file: A26F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
